// Code generated by protoc-gen-clone. DO NOT EDIT.

package user_pb

func (z *V1_Credential) Clone() *V1_Credential {
	if z == nil {
		return nil
	}
	zz := &V1_Credential{}
	return zz
}
func (z *V1) Clone() *V1 {
	if z == nil {
		return nil
	}
	zz := &V1{}
	zz.Id = z.Id
	zz.CreatedAtUs = z.CreatedAtUs
	zz.UpdatedAtUs = z.UpdatedAtUs
	zz.Name = z.Name
	zz.OrganizationID = z.OrganizationID
	zz0 := make([]*V1_Credential, len(z.Credentials))
	for i := range z.Credentials {
		zz0[i] = z.Credentials[i].Clone()
	}
	zz.Credentials = zz0
	return zz
}
