// Code generated by protoc-gen-setter. DO NOT EDIT.

package user_pb

func (z *V1) SetId(v string) *V1 {
	z.Id = v
	return z
}
func (z *V1) SetCreatedAtUs(v int64) *V1 {
	z.CreatedAtUs = v
	return z
}
func (z *V1) SetUpdatedAtUs(v int64) *V1 {
	z.UpdatedAtUs = v
	return z
}
func (z *V1) SetName(v string) *V1 {
	z.Name = v
	return z
}
func (z *V1) SetOrganizationID(v string) *V1 {
	z.OrganizationID = v
	return z
}
func (z *V1) SetCredentials(v []*V1_Credential) *V1 {
	z.Credentials = v
	return z
}
func (z *V1) AppendCredentials(v *V1_Credential) *V1 {
	z.Credentials = append(z.Credentials, v)
	return z
}
