// Code generated by protoc-gen-clone. DO NOT EDIT.

package upload_pb

func (z *V1) Clone() *V1 {
	if z == nil {
		return nil
	}
	zz := &V1{}
	zz.Id = z.Id
	zz.CreatedAtUs = z.CreatedAtUs
	zz.UpdatedAtUs = z.UpdatedAtUs
	zz.OrganizationID = z.OrganizationID
	zz.ProjectID = z.ProjectID
	zz.Name = z.Name
	zz.ObjectURL = z.ObjectURL
	zz.Size = z.Size
	zz.ContentType = z.ContentType
	return zz
}
