// Code generated by protoc-gen-setter. DO NOT EDIT.

package upload_pb

func (z *V1) SetId(v string) *V1 {
	z.Id = v
	return z
}
func (z *V1) SetCreatedAtUs(v int64) *V1 {
	z.CreatedAtUs = v
	return z
}
func (z *V1) SetUpdatedAtUs(v int64) *V1 {
	z.UpdatedAtUs = v
	return z
}
func (z *V1) SetOrganizationID(v string) *V1 {
	z.OrganizationID = v
	return z
}
func (z *V1) SetProjectID(v string) *V1 {
	z.ProjectID = v
	return z
}
func (z *V1) SetName(v string) *V1 {
	z.Name = v
	return z
}
func (z *V1) SetObjectURL(v string) *V1 {
	z.ObjectURL = v
	return z
}
func (z *V1) SetSize(v int64) *V1 {
	z.Size = v
	return z
}
func (z *V1) SetContentType(v string) *V1 {
	z.ContentType = v
	return z
}
