// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: resources/org/v1.proto

package org_pb

import (
	user "github.com/dstreamcloud/proto/pbgo/resources/user"
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type V1_Member_Role int32

const (
	V1_Member_READONLY  V1_Member_Role = 0
	V1_Member_TESTER    V1_Member_Role = 1
	V1_Member_DEVELOPER V1_Member_Role = 2
	V1_Member_ADMIN     V1_Member_Role = 3
)

// Enum value maps for V1_Member_Role.
var (
	V1_Member_Role_name = map[int32]string{
		0: "READONLY",
		1: "TESTER",
		2: "DEVELOPER",
		3: "ADMIN",
	}
	V1_Member_Role_value = map[string]int32{
		"READONLY":  0,
		"TESTER":    1,
		"DEVELOPER": 2,
		"ADMIN":     3,
	}
)

func (x V1_Member_Role) Enum() *V1_Member_Role {
	p := new(V1_Member_Role)
	*p = x
	return p
}

func (x V1_Member_Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (V1_Member_Role) Descriptor() protoreflect.EnumDescriptor {
	return file_resources_org_v1_proto_enumTypes[0].Descriptor()
}

func (V1_Member_Role) Type() protoreflect.EnumType {
	return &file_resources_org_v1_proto_enumTypes[0]
}

func (x V1_Member_Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use V1_Member_Role.Descriptor instead.
func (V1_Member_Role) EnumDescriptor() ([]byte, []int) {
	return file_resources_org_v1_proto_rawDescGZIP(), []int{0, 0, 0}
}

type V1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAtUs   int64        `protobuf:"varint,2,opt,name=createdAtUs,proto3" json:"createdAtUs,omitempty"`
	UpdatedAtUs   int64        `protobuf:"varint,3,opt,name=updatedAtUs,proto3" json:"updatedAtUs,omitempty"`
	Name          string       `protobuf:"bytes,11,opt,name=name,proto3" json:"name,omitempty"`
	CreatedByUser *user.V1     `protobuf:"bytes,12,opt,name=createdByUser,proto3" json:"createdByUser,omitempty"`
	Members       []*V1_Member `protobuf:"bytes,13,rep,name=members,proto3" json:"members,omitempty"`
}

func (x *V1) Reset() {
	*x = V1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resources_org_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *V1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1) ProtoMessage() {}

func (x *V1) ProtoReflect() protoreflect.Message {
	mi := &file_resources_org_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1.ProtoReflect.Descriptor instead.
func (*V1) Descriptor() ([]byte, []int) {
	return file_resources_org_v1_proto_rawDescGZIP(), []int{0}
}

func (x *V1) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *V1) GetCreatedAtUs() int64 {
	if x != nil {
		return x.CreatedAtUs
	}
	return 0
}

func (x *V1) GetUpdatedAtUs() int64 {
	if x != nil {
		return x.UpdatedAtUs
	}
	return 0
}

func (x *V1) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *V1) GetCreatedByUser() *user.V1 {
	if x != nil {
		return x.CreatedByUser
	}
	return nil
}

func (x *V1) GetMembers() []*V1_Member {
	if x != nil {
		return x.Members
	}
	return nil
}

type V1_Member struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *user.V1       `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Role V1_Member_Role `protobuf:"varint,2,opt,name=role,proto3,enum=org.V1_Member_Role" json:"role,omitempty"`
}

func (x *V1_Member) Reset() {
	*x = V1_Member{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resources_org_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *V1_Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*V1_Member) ProtoMessage() {}

func (x *V1_Member) ProtoReflect() protoreflect.Message {
	mi := &file_resources_org_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use V1_Member.ProtoReflect.Descriptor instead.
func (*V1_Member) Descriptor() ([]byte, []int) {
	return file_resources_org_v1_proto_rawDescGZIP(), []int{0, 0}
}

func (x *V1_Member) GetUser() *user.V1 {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *V1_Member) GetRole() V1_Member_Role {
	if x != nil {
		return x.Role
	}
	return V1_Member_READONLY
}

var File_resources_org_v1_proto protoreflect.FileDescriptor

var file_resources_org_v1_proto_rawDesc = []byte{
	0x0a, 0x16, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2f, 0x6f, 0x72, 0x67, 0x2f,
	0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6f, 0x72, 0x67, 0x1a, 0x17, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x76, 0x31,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd4, 0x02, 0x0a, 0x02, 0x56, 0x31, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x20, 0x0a,
	0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x55, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x55, 0x73, 0x12,
	0x20, 0x0a, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x55, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x55,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x0d, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x56, 0x31, 0x52, 0x0d, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42,
	0x79, 0x55, 0x73, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73,
	0x18, 0x0d, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x56, 0x31, 0x2e,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x1a,
	0x8b, 0x01, 0x0a, 0x06, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e,
	0x56, 0x31, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x56, 0x31, 0x2e,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04, 0x72, 0x6f, 0x6c,
	0x65, 0x22, 0x3a, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x41,
	0x44, 0x4f, 0x4e, 0x4c, 0x59, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x54, 0x45, 0x53, 0x54, 0x45,
	0x52, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x44, 0x45, 0x56, 0x45, 0x4c, 0x4f, 0x50, 0x45, 0x52,
	0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x44, 0x4d, 0x49, 0x4e, 0x10, 0x03, 0x42, 0x39, 0x5a,
	0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70,
	0x62, 0x67, 0x6f, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2f, 0x6f, 0x72,
	0x67, 0x3b, 0x6f, 0x72, 0x67, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_resources_org_v1_proto_rawDescOnce sync.Once
	file_resources_org_v1_proto_rawDescData = file_resources_org_v1_proto_rawDesc
)

func file_resources_org_v1_proto_rawDescGZIP() []byte {
	file_resources_org_v1_proto_rawDescOnce.Do(func() {
		file_resources_org_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_resources_org_v1_proto_rawDescData)
	})
	return file_resources_org_v1_proto_rawDescData
}

var file_resources_org_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_resources_org_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_resources_org_v1_proto_goTypes = []interface{}{
	(V1_Member_Role)(0), // 0: org.V1.Member.Role
	(*V1)(nil),          // 1: org.V1
	(*V1_Member)(nil),   // 2: org.V1.Member
	(*user.V1)(nil),     // 3: user.V1
}
var file_resources_org_v1_proto_depIdxs = []int32{
	3, // 0: org.V1.createdByUser:type_name -> user.V1
	2, // 1: org.V1.members:type_name -> org.V1.Member
	3, // 2: org.V1.Member.user:type_name -> user.V1
	0, // 3: org.V1.Member.role:type_name -> org.V1.Member.Role
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_resources_org_v1_proto_init() }
func file_resources_org_v1_proto_init() {
	if File_resources_org_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_resources_org_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*V1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resources_org_v1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*V1_Member); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_resources_org_v1_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resources_org_v1_proto_goTypes,
		DependencyIndexes: file_resources_org_v1_proto_depIdxs,
		EnumInfos:         file_resources_org_v1_proto_enumTypes,
		MessageInfos:      file_resources_org_v1_proto_msgTypes,
	}.Build()
	File_resources_org_v1_proto = out.File
	file_resources_org_v1_proto_rawDesc = nil
	file_resources_org_v1_proto_goTypes = nil
	file_resources_org_v1_proto_depIdxs = nil
}
