// Code generated by protoc-gen-clone. DO NOT EDIT.

package org_pb

func (z *V1_Member) Clone() *V1_Member {
	if z == nil {
		return nil
	}
	zz := &V1_Member{}
	zz.User = z.User.Clone()
	zz.Role = z.Role
	return zz
}
func (z *V1) Clone() *V1 {
	if z == nil {
		return nil
	}
	zz := &V1{}
	zz.Id = z.Id
	zz.CreatedAtUs = z.CreatedAtUs
	zz.UpdatedAtUs = z.UpdatedAtUs
	zz.Name = z.Name
	zz.CreatedByUser = z.CreatedByUser.Clone()
	zz0 := make([]*V1_Member, len(z.Members))
	for i := range z.Members {
		zz0[i] = z.Members[i].Clone()
	}
	zz.Members = zz0
	return zz
}
