// Code generated by protoc-gen-setter. DO NOT EDIT.

package org_pb

import (
	user "github.com/dstreamcloud/proto/pbgo/resources/user"
)

func (z *V1_Member) SetUser(v *user.V1) *V1_Member {
	z.User = v
	return z
}
func (z *V1_Member) SetRole(v V1_Member_Role) *V1_Member {
	z.Role = v
	return z
}
func (z *V1) SetId(v string) *V1 {
	z.Id = v
	return z
}
func (z *V1) SetCreatedAtUs(v int64) *V1 {
	z.CreatedAtUs = v
	return z
}
func (z *V1) SetUpdatedAtUs(v int64) *V1 {
	z.UpdatedAtUs = v
	return z
}
func (z *V1) SetName(v string) *V1 {
	z.Name = v
	return z
}
func (z *V1) SetCreatedByUser(v *user.V1) *V1 {
	z.CreatedByUser = v
	return z
}
func (z *V1) SetMembers(v []*V1_Member) *V1 {
	z.Members = v
	return z
}
func (z *V1) AppendMembers(v *V1_Member) *V1 {
	z.Members = append(z.Members, v)
	return z
}
