// Code generated by protoc-gen-setter. DO NOT EDIT.

package job_pb

func (z *V1_Pipeline) SetId(v string) *V1_Pipeline {
	z.Id = v
	return z
}
func (z *V1_Pipeline) SetCreatedAt(v int64) *V1_Pipeline {
	z.CreatedAt = v
	return z
}
func (z *V1_Pipeline) SetUpdatedAt(v int64) *V1_Pipeline {
	z.UpdatedAt = v
	return z
}
func (z *V1_Pipeline) SetTeamID(v string) *V1_Pipeline {
	z.TeamID = v
	return z
}
func (z *V1_Pipeline) SetProjectID(v string) *V1_Pipeline {
	z.ProjectID = v
	return z
}
func (z *V1_Pipeline) SetOwnerID(v string) *V1_Pipeline {
	z.OwnerID = v
	return z
}
func (z *V1_Pipeline) SetRemarks(v string) *V1_Pipeline {
	z.Remarks = v
	return z
}
func (z *V1_Pipeline) SetSettings(v *V1_Settings) *V1_Pipeline {
	z.Settings = v
	return z
}
func (z *V1_Pipeline) SetSource(v string) *V1_Pipeline {
	z.Source = v
	return z
}
func (z *V1_Pipeline) SetArguments(v map[string]string) *V1_Pipeline {
	z.Arguments = v
	return z
}
func (z *V1_Pipeline) PutArguments(k string, v string) *V1_Pipeline {
	z.Arguments[k] = v
	return z
}
func (z *V1_Pipeline) SetEnvironments(v map[string]string) *V1_Pipeline {
	z.Environments = v
	return z
}
func (z *V1_Pipeline) PutEnvironments(k string, v string) *V1_Pipeline {
	z.Environments[k] = v
	return z
}
func (z *V1_Job) SetId(v string) *V1_Job {
	z.Id = v
	return z
}
func (z *V1_Job) SetCreatedAt(v int64) *V1_Job {
	z.CreatedAt = v
	return z
}
func (z *V1_Job) SetUpdatedAt(v int64) *V1_Job {
	z.UpdatedAt = v
	return z
}
func (z *V1_Job) SetTeamID(v string) *V1_Job {
	z.TeamID = v
	return z
}
func (z *V1_Job) SetProjectID(v string) *V1_Job {
	z.ProjectID = v
	return z
}
func (z *V1_Job) SetOwnerID(v string) *V1_Job {
	z.OwnerID = v
	return z
}
func (z *V1_Job) SetPipelineID(v string) *V1_Job {
	z.PipelineID = v
	return z
}
func (z *V1_Job) SetAgentID(v string) *V1_Job {
	z.AgentID = v
	return z
}
func (z *V1_Job) SetStatus(v V1_Job_Status) *V1_Job {
	z.Status = v
	return z
}
func (z *V1_Job) SetSettings(v *V1_Settings) *V1_Job {
	z.Settings = v
	return z
}
func (z *V1_Job) SetSource(v string) *V1_Job {
	z.Source = v
	return z
}
func (z *V1_Job) SetArguments(v map[string]string) *V1_Job {
	z.Arguments = v
	return z
}
func (z *V1_Job) PutArguments(k string, v string) *V1_Job {
	z.Arguments[k] = v
	return z
}
func (z *V1_Job) SetEnvironments(v map[string]string) *V1_Job {
	z.Environments = v
	return z
}
func (z *V1_Job) PutEnvironments(k string, v string) *V1_Job {
	z.Environments[k] = v
	return z
}
func (z *V1_Settings) SetConcurrency(v int64) *V1_Settings {
	z.Concurrency = v
	return z
}
func (z *V1_Settings) SetTotal(v int64) *V1_Settings {
	z.Total = v
	return z
}
func (z *V1_Settings) SetStopAt(v int64) *V1_Settings {
	z.StopAt = v
	return z
}
