// Code generated by protoc-gen-setter. DO NOT EDIT.

package project_pb

import (
	dag "github.com/dstreamcloud/proto/pbgo/resources/dag"
)

func (z *V1) SetId(v string) *V1 {
	z.Id = v
	return z
}
func (z *V1) SetCreatedAtUs(v int64) *V1 {
	z.CreatedAtUs = v
	return z
}
func (z *V1) SetUpdatedAtUs(v int64) *V1 {
	z.UpdatedAtUs = v
	return z
}
func (z *V1) SetOrgID(v string) *V1 {
	z.OrgID = v
	return z
}
func (z *V1) SetCreatedByUserID(v string) *V1 {
	z.CreatedByUserID = v
	return z
}
func (z *V1) SetName(v string) *V1 {
	z.Name = v
	return z
}
func (z *V1) SetRemarks(v string) *V1 {
	z.Remarks = v
	return z
}
func (z *V1) SetEnvironments(v map[string]string) *V1 {
	z.Environments = v
	return z
}
func (z *V1) PutEnvironments(k string, v string) *V1 {
	z.Environments[k] = v
	return z
}
func (z *V1) SetSource(v *dag.V1_Release) *V1 {
	z.Source = v
	return z
}
