// Code generated by protoc-gen-setter. DO NOT EDIT.

package agent_pb

func (z *V1_Agent) SetId(v string) *V1_Agent {
	z.Id = v
	return z
}
func (z *V1_Agent) SetOrganizationID(v string) *V1_Agent {
	z.OrganizationID = v
	return z
}
func (z *V1_Agent) SetName(v string) *V1_Agent {
	z.Name = v
	return z
}
func (z *V1_Agent) SetToken(v string) *V1_Agent {
	z.Token = v
	return z
}
func (z *V1_Agent) SetStatus(v V1_Status) *V1_Agent {
	z.Status = v
	return z
}
