// Code generated by protoc-gen-setter. DO NOT EDIT.

package agent_pb

func (z *V1_Agent) SetId(v string) *V1_Agent {
	z.Id = v
	return z
}
func (z *V1_Agent) SetCreatedAt(v int64) *V1_Agent {
	z.CreatedAt = v
	return z
}
func (z *V1_Agent) SetUpdatedAt(v int64) *V1_Agent {
	z.UpdatedAt = v
	return z
}
func (z *V1_Agent) SetTeamID(v string) *V1_Agent {
	z.TeamID = v
	return z
}
func (z *V1_Agent) SetOwnerID(v string) *V1_Agent {
	z.OwnerID = v
	return z
}
func (z *V1_Agent) SetName(v string) *V1_Agent {
	z.Name = v
	return z
}
func (z *V1_Agent) SetToken(v string) *V1_Agent {
	z.Token = v
	return z
}
func (z *V1_Agent) SetStatus(v V1_Status) *V1_Agent {
	z.Status = v
	return z
}
